# Generated by Django 4.2.7 on 2023-12-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
