# Generated by Django 4.2.7 on 2023-12-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_trainer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='course',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_trainers/'),
        ),
    ]
